name: CI/CD - Production

on:
  pull_request:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test

      - name: Build Docker Image
        run: docker build -t secure-app .

      - name: Tag Version
        run: |
          git tag v1.${{ github.run_number }}
          git push origin --tags